//! End-to-end tests for the `#[protocol]` attribute: the generated trait (static
//! generic-bound surface), the erased `…Handle` and its two construction paths,
//! heterogeneous collections, generic-bound combining, and the `local` variant.

#![cfg(all(
    feature = "derive",
    feature = "dynamic-dispatch",
    feature = "tokio-runtime",
    feature = "tokio-lock",
    feature = "tokio-answer"
))]

use factories_actor::actor::Actor;
use factories_actor::actor::handle::{AnyActorHandle, AnyLocalActorHandle, TypedActorHandle};
use factories_actor::protocol;
use factories_actor::runtime::tokio::TokioTaskSpawner;
use factories_actor::spawn::ActorLauncher;

// -- A derived actor with two handlers -> two generated messages ----------------

#[derive(Actor)]
struct Calc {
    value: u32,
}

#[factories_actor::messages]
impl Calc {
    #[handler]
    fn add(&mut self, amount: u32) {
        self.value += amount;
    }

    #[handler]
    fn total(&mut self) -> u32 {
        self.value
    }
}

// -- Protocols ------------------------------------------------------------------

/// Shared protocol over both messages (`Add` and `Total` are generated by
/// `#[messages]` from the handler names).
#[protocol]
trait Counting {
    fn add(&self, msg: Add);
    fn total(&self, msg: Total);
}

/// Two narrow protocols, to exercise generic-bound combining (`impl A + B`).
#[protocol]
trait Adder {
    fn add(&self, msg: Add);
}

#[protocol]
trait Reader {
    fn total(&self, msg: Total);
}

/// A thread-local protocol: same messages, but the handle wraps an
/// `AnyLocalActorHandle` and is `!Send`.
#[protocol(local)]
trait LocalCounting {
    fn add(&self, msg: Add);
    fn total(&self, msg: Total);
}

// -- Helpers --------------------------------------------------------------------

async fn spawn_calc(value: u32) -> TypedActorHandle<Calc> {
    let handle: CalcHandle = ActorLauncher::default()
        .spawn_ready(&TokioTaskSpawner::current(), Calc { value })
        .await
        .expect("calc init is infallible");
    handle.into()
}

// -- Tests ----------------------------------------------------------------------

#[tokio::test]
async fn typed_handle_satisfies_protocol_generically() {
    // The static surface: a typed handle is accepted wherever `impl Counting` is.
    async fn drive(counter: impl Counting) -> u32 {
        counter.add(Add { amount: 5 }).tell().await.expect("tell");
        counter.total(Total).await.expect("ask")
    }

    let calc = spawn_calc(10).await;
    assert_eq!(drive(calc).await, 15);
}

#[tokio::test]
async fn erased_handle_from_typed_is_infallible() {
    let calc = spawn_calc(100).await;
    let counter: CountingHandle = calc.into();

    counter.add(Add { amount: 1 }).tell().await.expect("tell");
    assert_eq!(counter.total(Total).ask().await.expect("ask"), 101);
}

#[tokio::test]
async fn erased_handle_from_any_binds_via_registry() {
    let any: AnyActorHandle = spawn_calc(7).await.erase_type();
    let counter = CountingHandle::try_from(any).expect("Calc speaks Counting");

    assert_eq!(counter.total(Total).ask().await.expect("ask"), 7);
}

#[tokio::test]
async fn heterogeneous_collection_of_protocol_handles() {
    let a: CountingHandle = spawn_calc(1).await.into();
    let b = CountingHandle::try_from(spawn_calc(2).await.erase_type()).expect("speaks Counting");

    let counters: Vec<CountingHandle> = vec![a, b];
    let mut total = 0;
    for counter in &counters {
        total += counter.total(Total).ask().await.expect("ask");
    }
    assert_eq!(total, 3);
}

#[tokio::test]
async fn generic_bound_combining_is_free() {
    // No combined protocol needed: a typed handle whose actor handles both
    // message sets satisfies `impl Adder + Reader` directly.
    async fn drive(handle: impl Adder + Reader) -> u32 {
        handle.add(Add { amount: 3 }).tell().await.expect("tell");
        handle.total(Total).ask().await.expect("ask")
    }

    let calc = spawn_calc(40).await;
    assert_eq!(drive(calc).await, 43);
}

#[tokio::test]
async fn shared_protocol_handle_is_send_sync() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<CountingHandle>();
}

#[tokio::test]
async fn local_protocol_handle_works() {
    let calc = spawn_calc(20).await;

    // Built from a typed handle via the local erasure (no Send + Sync bound).
    let local: LocalCountingHandle = calc.into();
    local.add(Add { amount: 2 }).tell().await.expect("tell");
    assert_eq!(local.total(Total).ask().await.expect("ask"), 22);

    // Also constructible from an erased local handle via the registry.
    let any: AnyLocalActorHandle = spawn_calc(5).await.erase_type_local();
    let local2 = LocalCountingHandle::try_from(any).expect("Calc speaks LocalCounting");
    assert_eq!(local2.total(Total).ask().await.expect("ask"), 5);
}
