use crate::actor::dispatch::DispatchedActorMessage;
use alloc::boxed::Box;
use core::pin::Pin;
use thiserror::Error;

pub type ActorChannelSendResult = Result<(), ActorChannelSendError>;
pub type PinnedActorChannelSendFuture<'a> =
    Pin<Box<dyn Future<Output = ActorChannelSendResult> + Send + 'a>>;

/// Implementation of an actor channel.
///
/// Most channels will also implement `CreatableChannel` as a common extension.
///
/// # Sendability contract
/// [`DispatchedActorMessage`] is unconditionally `Send` as a carrier type. A channel
/// implementation that transports deliveries across threads must therefore verify
/// [`crate::message::envelope::MessageEnvelope::is_sendable`] before doing so and
/// reject the message with [`ActorChannelSendError::NotSendable`] otherwise.
/// Channels whose construction guarantees that sender and receiver stay on one
/// thread may skip the check.
#[must_use = "The message is not sent unless send or send_blocking is called"]
pub trait ActorChannel {
    /// Prepare sending a message through the channel.
    ///
    /// Depending on the channel implementation, this might apply routing of the message.
    fn prepare_send(&self, message: DispatchedActorMessage) -> impl ActorChannelSendable<'_>;
}

#[must_use = "The message is not sent unless send or send_blocking is called"]
pub(crate) trait DynActorChannel {
    fn prepare_send(
        &self,
        message: DispatchedActorMessage,
    ) -> Box<dyn DynActorChannelSendable<'_> + '_>;
}

impl<T> DynActorChannel for T
where
    T: ActorChannel,
{
    fn prepare_send(
        &self,
        message: DispatchedActorMessage,
    ) -> Box<dyn DynActorChannelSendable<'_> + '_> {
        Box::new(T::prepare_send(self, message))
    }
}

/// Sendable envelope generated by actor channels.
///
/// Send is one-way: a failed send does not return the message, unlike a raw channel. An
/// actor message can fail to be handled in ways the channel can't observe - the run loop
/// may crash after pulling from the channel but before invoking the handler, or partway
/// through. Returning the message on channel-level failure alone would be misleading,
/// since callers relying on it would have a silent bug for any failure past that point.
///
/// If you need retry or failover, retain your own copy (`Arc<Msg>` or `Clone`) before sending.
pub trait ActorChannelSendable<'a> {
    /// Send the prepared sendable asynchronously.
    fn send(self) -> impl Future<Output = ActorChannelSendResult> + Send;

    /// Send the prepared sendable blocking.
    fn blocking_send(self) -> ActorChannelSendResult;
}

pub trait DynActorChannelSendable<'a> {
    fn send(self: Box<Self>) -> PinnedActorChannelSendFuture<'a>;

    fn blocking_send(self: Box<Self>) -> ActorChannelSendResult;
}

impl<'a, T> DynActorChannelSendable<'a> for T
where
    T: ActorChannelSendable<'a> + 'a,
{
    fn send(self: Box<Self>) -> PinnedActorChannelSendFuture<'a> {
        let fut = T::send(*self);
        Box::pin(fut)
    }

    fn blocking_send(self: Box<Self>) -> ActorChannelSendResult {
        T::blocking_send(*self)
    }
}

/// Error generated when sending a message to an actor via the actor channel.
#[derive(Debug, Error)]
pub enum ActorChannelSendError {
    /// The actor has died and thus can no longer receive messages
    #[error("actor dead")]
    ActorDead,

    /// The actor's mailbox is full
    #[error("actor mailbox full")]
    MailboxFull,

    /// The message can not be routed to the actor.
    ///
    /// This can happen if a channel has no lane for the message
    /// or some internal configuration mismatch occurs.
    #[error("message is not routable")]
    Unroutable,

    /// The message cannot cross threads to reach this actor.
    ///
    /// Returned by channels that transport messages across threads when the
    /// envelope is not sendable (`!Send` message, or `!Send` answer sender on
    /// an ask).
    #[error("message is not sendable across threads")]
    NotSendable,

    /// Other, channel-specific error.
    #[error(transparent)]
    Other(Box<dyn core::error::Error + Send + Sync>),
}
