use crate::actor::dispatch::{ActorMessageDispatcher, DispatchedActorMessage};
use crate::actor::rtti::ActorRtti;
use crate::message::Message;
use crate::message::envelope::MessageEnvelope;
use crate::message::rtti::MessageRtti;
use alloc::boxed::Box;
use core::marker::PhantomData;
use core::pin::Pin;
use thiserror::Error;

pub mod dispatch;
pub mod handle;
pub mod identity;
pub mod rtti;

/// The heart of the actor system. Defines a struct as being an actor.
pub unsafe trait Actor: 'static {
    const RTTI: &'static ActorRtti;

    type Channel: ActorChannel;

    /// The binder used to bind message handlers for dynamically dispatched messages.
    ///
    /// If the message handler target is known at compile time, the binder might not be
    /// invoked.
    type RuntimeBinder: ActorRuntimeBinder;

    /// The lock strategy used to gain access to the actor state.
    type LockStrategy: LockStrategy<Self> + 'static;

    /// The run loop that is used to drive this actor.
    type RunLoop: ActorRunLoop<Self>;
}

/// Lock strategy that encapsulates the locking of the actor state.
pub trait LockStrategy<A: Actor + ?Sized> {
}

/// Access mode that defines how a given lock strategy is used to obtain an actor lock.
///
/// Acquisition is async so the dispatch path can serialize lock acquisition
/// through the mailbox reader: while a contended acquire is pending the run
/// loop can still drive in-flight handler futures, but cannot pull a fresh
/// message from the mailbox and race ahead of the pending acquire.
pub trait AccessMode<A: Actor + ?Sized> {
    /// The resulting lock type.
    type Guard<'a>
    where
        Self: 'a;

    fn acquire<'a>(
        lock_strategy: &'a A::LockStrategy,
    ) -> impl Future<Output = Self::Guard<'a>>
    where
        Self: 'a;
}

pub type ActorChannelSendResult = Result<(), (ActorChannelSendError, DispatchedActorMessage)>;
pub type PinnedActorChannelSendFuture<'a> =
    Pin<Box<dyn Future<Output = ActorChannelSendResult> + Send + 'a>>;

/// Implementation of an actor channel.
#[must_use = "The message is not sent unless send or send_blocking is called"]
pub trait ActorChannel {
    /// Prepare sending a message through the channel.
    ///
    /// Depending on the channel implementation, this might apply routing of the message.
    fn prepare_send(&self, message: DispatchedActorMessage) -> impl ActorChannelSendable<'_>;
}

#[must_use = "The message is not sent unless send or send_blocking is called"]
pub(crate) trait DynActorChannel {
    fn prepare_send(
        &self,
        message: DispatchedActorMessage,
    ) -> Box<dyn DynActorChannelSendable<'_> + '_>;
}

impl<T> DynActorChannel for T
where
    T: ActorChannel,
{
    fn prepare_send(
        &self,
        message: DispatchedActorMessage,
    ) -> Box<dyn DynActorChannelSendable<'_> + '_> {
        Box::new(T::prepare_send(self, message))
    }
}

/// Sendable envelope generated by actor channels.
pub trait ActorChannelSendable<'a> {
    /// Send the prepared sendable asynchronously.
    fn send(self) -> impl Future<Output = ActorChannelSendResult> + Send;

    /// Send the prepared sendable blocking.
    fn blocking_send(self) -> ActorChannelSendResult;
}

pub trait DynActorChannelSendable<'a> {
    fn send(self: Box<Self>) -> PinnedActorChannelSendFuture<'a>;

    fn blocking_send(self: Box<Self>) -> ActorChannelSendResult;
}

impl<'a, T> DynActorChannelSendable<'a> for T
where
    T: ActorChannelSendable<'a> + 'a,
{
    fn send(self: Box<Self>) -> PinnedActorChannelSendFuture<'a> {
        let fut = T::send(*self);
        Box::pin(fut)
    }

    fn blocking_send(self: Box<Self>) -> ActorChannelSendResult {
        T::blocking_send(*self)
    }
}

/// Error generated when sending a message to an actor via the actor channel.
#[derive(Debug, Error)]
pub enum ActorChannelSendError {
    /// The actor has died and thus can no longer receive messages
    #[error("actor dead")]
    ActorDead,

    /// The actor's mailbox is full
    #[error("actor mailbox full")]
    MailboxFull,

    /// Other, channel-specific error.
    #[error(transparent)]
    Other(Box<dyn core::error::Error + Send + Sync>),
}

/// Context passed to a message handler of an actor.
pub struct MessageHandlerContext<'a, M: Message, A: Actor + ?Sized, E: AccessMode<A> + 'a> {
    actor_access: E::Guard<'a>,
    envelope: MessageEnvelope,
    _data: PhantomData<(M, fn() -> A, E)>,
}

impl<'a, M: Message, A: Actor + ?Sized, E: AccessMode<A>> MessageHandlerContext<'a, M, A, E> {
    /// Create a new message handler context.
    ///
    /// Creation only succeeds if the envelope actually carries the correct message
    /// type.
    pub fn new(
        actor_access: E::Guard<'a>,
        envelope: MessageEnvelope,
    ) -> Result<Self, MessageEnvelope> {
        if envelope.rtti() != M::RTTI {
            // Type mismatch
            return Err(envelope);
        }

        // SAFETY: We checked that M is indeed the payload type of the envelope
        Ok(unsafe { Self::new_unchecked(actor_access, envelope) })
    }

    /// Create a new message handler context.
    ///
    /// # Safety
    /// The caller is responsible for ensuring that the envelope actually carries a message
    /// of type `M`.
    pub unsafe fn new_unchecked(actor_access: E::Guard<'a>, envelope: MessageEnvelope) -> Self {
        Self {
            actor_access,
            envelope,
            _data: PhantomData,
        }
    }
}

/// Implementation of a message handler for an actor.
pub trait MessageHandler<M: Message>: Actor {
    type AccessMode: AccessMode<Self> + 'static;

    fn handle<'a>(
        ctx: MessageHandlerContext<'a, M, Self, Self::AccessMode>,
    ) -> impl Future<Output = ()> + 'a;
}

/// Implementation that binds handlers to messages.
///
/// Runtime binders are required to be Send + Sync as they are expected to only
/// look up function pointers and ensure that thread safe dispatch is possible.
///
/// In other words, a runtime binder must be the instance that itself performs
/// the thread safety checks and as such must be thread safe itself.
///
/// # Safety
/// The implementation must ensure that the bound handler will be able to handle
/// envelopes of the given message type and that the handler is invokable on the
/// actor thread.
pub unsafe trait ActorRuntimeBinder: Send + Sync {
    /// Bind the handler for the given message.
    ///
    /// Note that this intentionally doesn't have access to the actor state,
    /// as the binding happens on the caller side.
    ///
    /// Note that this must also validate that the message can be dispatched
    /// to the actor thread. If the message is not `Send`, then this must
    /// return `None` if the dispatcher can't guarantee that the message
    /// is accessed on the thread this is called from.
    fn bind(&self, message: &MessageRtti) -> Option<ActorMessageDispatcher>;
}

pub trait ActorRunLoop<A: Actor + ?Sized> {
    /// The dispatch context type owned by the run loop.
    ///
    /// `'static` is required so the dispatcher's fn-pointer signature can stay
    /// late-bound in the call-site lifetime (HRTB-coercible). In practice the
    /// run loop owns its dispatch context outright, so this is rarely a real
    /// constraint.
    type DispatchContext: ActorRunLoopDispatchContext<A> + 'static;
}

/// The dispatch-side view of an actor's run loop.
///
/// A reference to this type is what the dispatcher casts the opaque
/// [`crate::actor::dispatch::DispatchContextPtr`] back into.
pub trait ActorRunLoopDispatchContext<A: Actor + ?Sized> {
    /// The lock strategy used to acquire access to the actor state.
    fn lock_strategy(&self) -> &A::LockStrategy;
}
