//! Concrete implementations: channels, run loops and task spawners.

#[cfg(any(feature = "tokio-runtime", feature = "tokio-lock"))]
pub mod tokio;

#[cfg(feature = "dynamic-dispatch")]
pub mod registry;

pub mod concurrent_loop;
pub mod defaults;
pub mod init;
pub mod lock;
pub mod loop_support;
pub mod result;
pub mod sequential_loop;
pub mod template;

/// Register a dynamically dispatched message handler *if* the
/// `dynamic-dispatch` feature is enabled; expands to nothing otherwise.
///
/// This is the macro counterpart of the [`defaults`] aliases: code generated
/// by the `#[messages]` attribute cannot see this crate's features, so it
/// emits this registration unconditionally and lets the feature decide here.
/// Also useful for hand-written handlers that must compile with and without
/// the feature.
#[cfg(feature = "dynamic-dispatch")]
#[macro_export]
macro_rules! register_dynamic_handler_if_enabled {
    ($actor:ty, $message:ty) => {
        $crate::register_dynamic_handler!($actor, $message);
    };
}

/// Register a dynamically dispatched message handler *if* the
/// `dynamic-dispatch` feature is enabled; expands to nothing otherwise.
///
/// The feature is disabled, so this expands to nothing.
#[cfg(not(feature = "dynamic-dispatch"))]
#[macro_export]
macro_rules! register_dynamic_handler_if_enabled {
    ($actor:ty, $message:ty) => {};
}

/// Emit the typed-handle method `impl` block generated by `#[messages]` *if* the
/// `tokio-answer` feature is enabled; expands to nothing otherwise.
///
/// The generated methods return [`MessageCall`](crate::actor::handle::MessageCall),
/// whose machinery is built on the answer channel and so lives behind
/// `tokio-answer`. Like [`register_dynamic_handler_if_enabled!`], this lets the
/// feature-blind macro output defer the feature decision to the library.
#[cfg(feature = "tokio-answer")]
#[macro_export]
macro_rules! typed_handle_methods_if_enabled {
    ($($body:tt)*) => { $($body)* };
}

/// Emit the typed-handle method `impl` block generated by `#[messages]` *if* the
/// `tokio-answer` feature is enabled; expands to nothing otherwise.
///
/// The feature is disabled, so this expands to nothing.
#[cfg(not(feature = "tokio-answer"))]
#[macro_export]
macro_rules! typed_handle_methods_if_enabled {
    ($($body:tt)*) => {};
}
